NAME: 'a2c_scratch'
TYPE: 'a2c'

MODEL:
  LOSS: 'huber'
  INIT: 'xavier'
  ARCH: [512, 256, 64]
#  LOAD_FILE: 'weights\double_dqn_experiment_1\double_dqn_experiment_1-epoch_best.ckpt'
TRAIN:
  MAX_EPISODES: 200
  WAIT_EPISODES: 1
  MEMORY_LEN: 20000

HYPERPARAMS:
  LEARNING_RATE: 0.00025
  GAMMA: 1.
  BATCH_SIZE: 64
